export GCP_ACCOUNT_FILE_JSON="/home/ehron/.gcloud/ekg-image-test.json"
export GCP_ZONE="us-east1-b"
export GCP_PROJECT_ID="ekg-image-test"

export PACKER_ENVIRONMENT="test"
export VCS_NAME="norhe"
export CONSUL_VERSION="0.9.2"
export CONSUL_ENT_URL="not_used"
export VAULT_VERSION="0.8.3"
export VAULT_ENT_URL="not_used"
export NOMAD_VERSION="0.6.3"
export NOMAD_ENT_URL="not_used"
export DISTRIBUTION="testing"
