require 'rake'
require 'rspec/core/rake_task'
require 'json'
require 'pathname'
require 'rainbow'
require 'rspec/core/rake_task'
require 'uri'

desc 'Run serverspec tests'
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/*_spec.rb'
end

desc 'Validate Templates'
task :validate do
  Pathname.glob('*.json').sort.each do |template|
    puts Rainbow("Validating #{template}...").green
    unless system "packer validate #{template}"
      puts Rainbow("#{template} is not a valid packer template").red
      raise "#{template} is not a valid packer template"
    end
  end
end

desc 'Build Templates'
task :build do
  Pathname.glob('*.json').sort.each do |template|
    unless system "packer build #{template}"
      puts Rainbow("#{template} build failed").red
      raise "#{template} built succesfully"
    end
  end
end
