# -*- mode: ruby -*-
# vi: set ft=ruby :

# base box selection
base_box = ENV['BASE_BOX'] || "bento/ubuntu-16.04"

# consul variable defaults
consul_user = ENV['CONSUL_USER'] || "consul"
consul_comment = ENV['CONSUL_COMMENT'] || ""
consul_group = ENV['CONSUL_GROUP'] || "consul"
consul_home = ENV['CONSUL_HOME'] || "/srv/consul"
consul_version = ENV['CONSUL_VERSION'] || "0.9.2"
consul_download_url = ENV['CONSUL_DOWNLOAD_URL'] || "https://releases.hashicorp.com/consul/#{consul_version}/consul_#{consul_version}_linux_amd64.zip"

# nomad variable defaults
nomad_user = ENV['NOMAD_USER'] || "nomad"
nomad_comment = ENV['NOMAD_COMMENT'] || ""
nomad_group = ENV['NOMAD_GROUP'] || "nomad"
nomad_home = ENV['NOMAD_HOME'] || "/srv/nomad"
nomad_version = ENV['NOMAD_VERSION'] || "0.6.0"
nomad_download_url = ENV['NOMAD_DOWNLOAD_URL'] || "https://releases.hashicorp.com/nomad/#{nomad_version}/nomad_#{nomad_version}_linux_amd64.zip"

$script = <<SCRIPT
# Set hostname's IP to make advertisement work
sudo sed -i -e "s/.*nomad.*/$(ip route get 1 | awk '{print $NF;exit}') nomad/" /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|
  # use vagrant insecure public key
  # important: comment this out to restrict access
  config.ssh.insert_key = false

  # use base_box set at the top of this file
  config.vm.box = base_box
  config.vm.hostname = "bastion"
  config.vm.provision "shell", inline: $script, privileged: false

  # copy the consul and nomad directories to the vm
  config.vm.provision "file", source: "../consul", destination: "/tmp"
  config.vm.provision "file", source: "../nomad", destination: "/tmp"

  # bootstrap the vm
  config.vm.provision "shell", path: "../shared/scripts/base.sh"
  config.vm.provision "shell", path: "../shared/scripts/base-aws.sh"
  config.vm.provision "shell", path: "../shared/scripts/setup-user.sh",
    env: {
      "USER" => consul_user,
      "COMMENT" => consul_comment,
      "GROUP" => consul_group,
      "HOME" => consul_home
    }
  config.vm.provision "shell", path: "../shared/scripts/setup-user.sh",
    env: {
      "USER" => nomad_user,
      "COMMENT" => nomad_comment,
      "GROUP" => nomad_group,
      "HOME" => nomad_home
    }

  # install consul
  config.vm.provision "shell", path: "../consul/scripts/install-consul.sh",
    env: {
      "VERSION" => consul_version,
      "URL" => consul_download_url
    }
  config.vm.provision "shell", path: "../consul/scripts/install-consul-systemd.sh"

  # install nomad
  config.vm.provision "shell", path: "../nomad/scripts/install-nomad.sh",
    env: {
      "VERSION" => nomad_version,
      "URL" => nomad_download_url
    }
  config.vm.provision "shell", path: "../nomad/scripts/install-nomad-systemd.sh"

  # cleanup on the way out
  config.vm.provision "shell", path: "../shared/scripts/cleanup.sh"
  config.vm.provision "shell", path: "../shared/scripts/cleanup-aws.sh"

  # Increase memory for Parallels Desktop
  config.vm.provider "parallels" do |p, o|
    p.memory = "1024"
  end

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "1024"
    end
  end
end
