# -*- mode: ruby -*-
# vi: set ft=ruby :

# base box selection
base_box = ENV['BASE_BOX'] || "bento/ubuntu-16.04"

# consul variable defaults
consul_user = ENV['CONSUL_USER'] || "consul"
consul_comment = ENV['CONSUL_COMMENT'] || ""
consul_group = ENV['CONSUL_GROUP'] || "consul"
consul_home = ENV['CONSUL_HOME'] || "/srv/consul"
consul_version = ENV['CONSUL_VERSION'] || "0.8.0"
consul_download_url = ENV['CONSUL_ENT_URL'] || "https://releases.hashicorp.com/consul/#{consul_version}/consul_#{consul_version}_linux_amd64.zip"
consul_server = ENV['CONSUL_SERVER'] || "true"

Vagrant.configure("2") do |config|
  # use vagrant insecure public key
  # important: comment this out to restrict access
  config.ssh.insert_key = false

  # use base_box set at the top of this file
  config.vm.box = base_box
  config.vm.hostname = "consul"

  # copy the consul directory to the vm
  config.vm.provision "file", source: "../consul", destination: "/tmp"

  # bootstrap the vm
  config.vm.provision "shell", path: "../shared/scripts/base.sh"
  config.vm.provision "shell", path: "../shared/scripts/setup-user.sh",
    env: {
      "USER" => consul_user,
      "COMMENT" => consul_comment,
      "GROUP" => consul_group,
      "HOME" => consul_home
    }

  # install consul
  config.vm.provision "shell", path: "scripts/install-consul.sh",
    env: {
      "USER" => consul_user,
      "GROUP" => consul_group,
      "VERSION" => consul_version,
      "URL" => consul_download_url,
      "SERVER" => consul_server
    }
  config.vm.provision "shell", path: "scripts/install-consul-systemd.sh"

  # cleanup on the way out
  config.vm.provision "shell", path: "../shared/scripts/cleanup.sh"

  # Increase memory for Parallels Desktop
  config.vm.provider "parallels" do |p, o|
    p.memory = "1024"
  end

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "1024"
    end
  end
end
